# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VTNetworkHelperDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VTNetworkHelperDemo
  pod 'AFNetworking', '~> 3.0'
  target 'VTNetworkHelperDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VTNetworkHelperDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
